services:
  postgres:
    image: postgres:16
    container_name: board-vault-db
    environment:
      POSTGRES_DB: boardvault
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
